{
	"tableCnt":3,
	"tplIdx":1,
	"nav":true,
	"query":true,
	"cache":{
		"TPL_VIEW_1":{
			"title":"","size":60,"table":"SM050","tableDesc":"SM050","meta":[{
				"FIELD":"SM050_02","FIELD_DESC":"模型編號","FIELD_EDITOR":"none"
			},{
				"FIELD":"SM050_03","FIELD_DESC":"模型名稱","FIELD_EDITOR":"none"
			}]
		},
		"TPL_VIEW_3":{
			"title":"SM050","size":120,"table":"SM050","tableDesc":"SM050","meta":[{
				"FIELD":"SM050_02","FIELD_DESC":"模型編號","FIELD_EDITOR":"none"
			},{
				"FIELD":"SM050_03","FIELD_DESC":"模型名稱","FIELD_EDITOR":"none"
			}]
		},
		"TPL_VIEW_5":{
			"title":"SM050","size":"","table":"SM050","tableDesc":"SM050","meta":[{
				"FIELD":"SM050_02","FIELD_DESC":"模型編號","FIELD_EDITOR":"none"
			},{
				"FIELD":"SM050_03","FIELD_DESC":"模型名稱","FIELD_EDITOR":"none"
			},{
				"FIELD":"SM050_04","FIELD_DESC":"工廠類","FIELD_EDITOR":"none"
			},{
				"FIELD":"SM050_05","FIELD_DESC":"工廠方法","FIELD_EDITOR":"none"
			},{
				"FIELD":"SM050_06","FIELD_DESC":"工廠用模型","FIELD_EDITOR":"none"
			},{
				"FIELD":"SM050_07","FIELD_DESC":"組裝后委托","FIELD_EDITOR":"none"
			},{
				"FIELD":"SM050_08","FIELD_DESC":"實用需池化","FIELD_EDITOR":"none"
			},{
				"FIELD":"SM050_09","FIELD_DESC":"修改時間","FIELD_EDITOR":"none"
			}]
		},
		"TPL_VIEW_6":{
			"title":"SM055","size":"","table":"SM055","tableDesc":"SM055","meta":[{
				"FIELD":"SM055_03","FIELD_DESC":"數據表名","FIELD_EDITOR":"none"
			},{
				"FIELD":"SM055_04","FIELD_DESC":"指定owner","FIELD_EDITOR":"none"
			}]
		},
		"TPL_VIEW_7":{
			"title":"SM060","size":"","table":"SM060","tableDesc":"SM060","meta":[{
				"FIELD":"SM060_03","FIELD_DESC":"業務ID","FIELD_EDITOR":"none"
			},{
				"FIELD":"SM060_04","FIELD_DESC":"控制順序","FIELD_EDITOR":"none"
			}]
		}
	},
	"mname":"SM050",
	"requires":["layout.CellLayout","layout.TableLayout","form.LabelField","form.Label","form.Combo","form.Button","panel.Window","grid.Grid","data.DataUnit","core.Container","form.QueryForm","form.Form"]
}